### ISSUE TITLE
A hard question

### ISSUE THREAD

**Issue by Lay-best** [zhiyuanyou/SAFECount#18]
Hello , when I run the order that : 'sh test_torch.sh 1 1', a error was found:
`ModuleNotFoundError: No module named 'datasets'`
Could you tell me how to address the error , please!

**Comment by zhiyuanyou** [comment]
Hi~

Could you show your directory of experiments using "pwd", and show the content of "test_torch.sh"?

**Comment by zhiyuanyou** [comment]
Hi~ 
You are on a Windows system, for which the environment variable **_PYTHONPATH_** could not be add using shell scripts.
There are 2 options: 
- (1) Set **_PYTHONPATH_** as **_the path of SAFECount-main directory_** to the environment variable.
- (2) Change to a Linux system. 
I suggest option (2), since all codes have been verified on Linux system.
