### ISSUE TITLE
Query - How to deal with the original image size and examplar scales

### ISSUE THREAD

**Issue by m-zheng** [zhiyuanyou/SAFECount#19]
Hi, thanks for sharing the source code for your paper. 

I am struggling to understand the reason to make the scaled query image size dividable by 16. 

https://github.com/zhiyuanyou/SAFECount/blob/318ae8872f960257f22bd6c861414d45829a7260/models/safecount.py#L63-L64

Suppose the examplar scale is `0.8` and the query image size is `520 * 520`. Its scaled query image size becomes `409.6 * 409.6`. Applying `int(409.6)` can lead to `409 * 409`.  Your implementation above will lead to `400 * 400`. Can you kindly share the reason behind it?

**Comment by zhiyuanyou** [comment]
Hi~

We use the feature from _**layer_1, layer_2, & layer_3 of resnet18**_. The features from these 3 layers have _**the stride of 4, 8, & 16**_, respectively. 

As stated in the paper, these 3 features need to be _**resized to the same size**_, and then concatenated together. **_The resize operation is done using stride, instead of a given size_**. 

Therefore, **_if the image size could not be divided by 16, the 3 resized features will have different sizes_**, thus can not be concatenated together.

**Comment by m-zheng** [comment]
Thanks for your help. It makes sense now.

Following by that, have you considered using the original image to get features from resnet18 and rescale them afterwards? In other words, have you considered the difference between 
1. `resnet18(resize(image))`
2. `resize(resnet18(image))`

**Comment by zhiyuanyou** [comment]
Not yet.&nbsp;


You can do this comparison to see which one is better.&nbsp;



---Original---
From: "Minghua ***@***.***&gt;
Date: Sun, Apr 23, 2023 18:31 PM
To: ***@***.***&gt;;
Cc: "You ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zhiyuanyou/SAFECount] Query - How to deal with the originalimage size and examplar scales (Issue #19)




 
Thanks for your help. It makes sense now.
 
Following by that, have you considered using the original image to get features from resnet18 and rescale them afterwards? In other words, have you considered the difference between
  
resnet18(resize(image))
 
resize(resnet18(image))
