### ISSUE TITLE
Query - Implementaion of weighted feature aggregation

### ISSUE THREAD

**Issue by m-zheng** [zhiyuanyou/SAFECount#25]
Hi,

I am trying to understand the implementation of your equation 5, 6 and 7 in your paper, and would be thankful if you can help.

![image](https://github.com/zhiyuanyou/SAFECount/assets/18236342/61bccdc3-2de2-43e2-a0c7-9ed919da9b51)
![image](https://github.com/zhiyuanyou/SAFECount/assets/18236342/e742493b-fd34-4e4b-8e86-697c34d5ee26)

According to your paper, the support feature **_f<sub>S</sub>_** is flipped before being used to convolve the **_R_**. However, there is a `1x1` convolution (line 247 below) applied on the support feature **_f<sub>S</sub>_**  before implementing the equation 5. Are you using the projected support feature **_f<sub>S</sub>_** for the equation 5?
https://github.com/zhiyuanyou/SAFECount/blob/de067f9f1ca2caea432dd4c2e6d9ec9b2a169ebf/models/safecount.py#L238-L262

Additionally, there is another `1x1` convolution (line 261) after implementing the equation 6. Are you using the projected **_f<sub>R</sub>_** to implement your equation 7?

**Comment by zhiyuanyou** [comment]
Yes, you are right. 

This implementation is modified according to `nn.MultiheadAttention()`. 

Since we want to implement this module using a multi-head form, we need to project a feature (`C x H x W`) to `N` sub-features (`N x C / N x H x W`) as `N` heads. Then we implement weighted feature aggregation **_within each head_**, finally **_aggregate the features of all heads_** together.

**Comment by m-zheng** [comment]
Thanks for your help. It makes perfect sense now.
