### ISSUE TITLE
Pretrain phase CARPK

### ISSUE THREAD

**Issue by perladoubinsky** [zhiyuanyou/SAFECount#28]
Hello and thanks for the nice work, 
I am having trouble reproducing the results of the pretrain phase for cross-dataset generalization on CARPK (MAE: 17.78, RMSE: 20.95). Could you specify which car samples of FSC147 you removed from the training set ? Also could you give more information on how to run the evaluation of  the pretrain phase model on CARPK (i.e do you use the config file in the finetune folder) ? Thank you!

**Comment by zhiyuanyou** [comment]
1. The samples are removed manually. I am sorry that I could not provide specific file names since it is too far from now, and I have graduated from SJTU where I finished this work. 
2. Yes. The results are evaluated under the `finetune` folder, but without training, just loading the pretrained weights.
